// Auto-generated by VibeStack — SLOT markers replaced by LLM during code generation
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_authenticated/comments')({
  component: CommentsListPage,
})

function CommentsListPage() {
  // {/* SLOT: LIST_PAGE — LLM fills component body for entity: comments */}
  return <div className="p-4">Loading comments...</div>
}
