// Auto-generated by VibeStack — SLOT markers replaced by LLM during code generation
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_authenticated/entities')({
  component: EntitiesListPage,
})

function EntitiesListPage() {
  // {/* SLOT: LIST_PAGE — LLM fills component body for entity: entities */}
  return <div className="p-4">Loading entities...</div>
}
