// Auto-generated by VibeStack — SLOT markers replaced by LLM during code generation
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_authenticated/menu-items')({
  component: MenuItemsListPage,
})

function MenuItemsListPage() {
  // {/* SLOT: LIST_PAGE — LLM fills component body for entity: menu_items */}
  return <div className="p-4">Loading menu-items...</div>
}
