// Auto-generated by VibeStack — SLOT markers replaced by LLM during code generation
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_authenticated/menu-categories/$id')({
  component: MenuCategoriesDetailPage,
})

function MenuCategoriesDetailPage() {
  // {/* SLOT: DETAIL_PAGE — LLM fills component body for entity: menu_categories */}
  return <div className="p-4">Loading menu_categories detail...</div>
}
