// Auto-generated by VibeStack — SLOT markers replaced by LLM during code generation
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_authenticated/menu-items/$id')({
  component: MenuItemsDetailPage,
})

function MenuItemsDetailPage() {
  // {/* SLOT: DETAIL_PAGE — LLM fills component body for entity: menu_items */}
  return <div className="p-4">Loading menu_items detail...</div>
}
