// Auto-generated by VibeStack — SLOT markers replaced by LLM during code generation
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_authenticated/order-items/$id')({
  component: OrderItemsDetailPage,
})

function OrderItemsDetailPage() {
  // {/* SLOT: DETAIL_PAGE — LLM fills component body for entity: order_items */}
  return <div className="p-4">Loading order_items detail...</div>
}
