// Auto-generated by VibeStack — SLOT markers replaced by LLM during code generation
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_authenticated/orders')({
  component: OrdersListPage,
})

function OrdersListPage() {
  // {/* SLOT: LIST_PAGE — LLM fills component body for entity: orders */}
  return <div className="p-4">Loading orders...</div>
}
