// Auto-generated by VibeStack — SLOT markers replaced by LLM during code generation
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_authenticated/orders/$id')({
  component: OrdersDetailPage,
})

function OrdersDetailPage() {
  // {/* SLOT: DETAIL_PAGE — LLM fills component body for entity: orders */}
  return <div className="p-4">Loading orders detail...</div>
}
