// Auto-generated by VibeStack — SLOT markers replaced by LLM during code generation
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_authenticated/order-items')({
  component: OrderItemsListPage,
})

function OrderItemsListPage() {
  // {/* SLOT: LIST_PAGE — LLM fills component body for entity: order_items */}
  return <div className="p-4">Loading order-items...</div>
}
