// Auto-generated by VibeStack — SLOT markers replaced by LLM during code generation
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_authenticated/pages/$id')({
  component: PagesDetailPage,
})

function PagesDetailPage() {
  // {/* SLOT: DETAIL_PAGE — LLM fills component body for entity: pages */}
  return <div className="p-4">Loading pages detail...</div>
}
