// Auto-generated by VibeStack — SLOT markers replaced by LLM during code generation
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_authenticated/posts/$id')({
  component: PostsDetailPage,
})

function PostsDetailPage() {
  // {/* SLOT: DETAIL_PAGE — LLM fills component body for entity: posts */}
  return <div className="p-4">Loading posts detail...</div>
}
