// Auto-generated by VibeStack — SLOT markers replaced by LLM during code generation
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_authenticated/posts')({
  component: PostsListPage,
})

function PostsListPage() {
  // {/* SLOT: LIST_PAGE — LLM fills component body for entity: posts */}
  return <div className="p-4">Loading posts...</div>
}
