// Auto-generated by VibeStack — SLOT markers replaced by LLM during code generation
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_authenticated/reservations')({
  component: ReservationsListPage,
})

function ReservationsListPage() {
  // {/* SLOT: LIST_PAGE — LLM fills component body for entity: reservations */}
  return <div className="p-4">Loading reservations...</div>
}
