// Auto-generated by VibeStack — SLOT markers replaced by LLM during code generation
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_authenticated/reservations/$id')({
  component: ReservationsDetailPage,
})

function ReservationsDetailPage() {
  // {/* SLOT: DETAIL_PAGE — LLM fills component body for entity: reservations */}
  return <div className="p-4">Loading reservations detail...</div>
}
