// Auto-generated by VibeStack — SLOT markers replaced by LLM during code generation
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_authenticated/restaurant-tables')({
  component: RestaurantTablesListPage,
})

function RestaurantTablesListPage() {
  // {/* SLOT: LIST_PAGE — LLM fills component body for entity: restaurant_tables */}
  return <div className="p-4">Loading restaurant-tables...</div>
}
