// Auto-generated by VibeStack — SLOT markers replaced by LLM during code generation
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_authenticated/services-pages/$id')({
  component: ServicesPageDetailPage,
})

function ServicesPageDetailPage() {
  // {/* SLOT: DETAIL_PAGE — LLM fills component body for entity: services_page */}
  return <div className="p-4">Loading services_page detail...</div>
}
