// Auto-generated by VibeStack — SLOT markers replaced by LLM during code generation
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_authenticated/site-settings')({
  component: SiteSettingsListPage,
})

function SiteSettingsListPage() {
  // {/* SLOT: LIST_PAGE — LLM fills component body for entity: site_settings */}
  return <div className="p-4">Loading site-settings...</div>
}
