// Auto-generated by VibeStack — SLOT markers replaced by LLM during code generation
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_authenticated/testimonials')({
  component: TestimonialsListPage,
})

function TestimonialsListPage() {
  // {/* SLOT: LIST_PAGE — LLM fills component body for entity: testimonials */}
  return <div className="p-4">Loading testimonials...</div>
}
