/* eslint-disable */
// @ts-nocheck
// This file is auto-generated by VibeStack — do not edit manually

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AboutImport } from './routes/about'
import { Route as ContactImport } from './routes/contact'
import { Route as EntitiesListImport } from './routes/entities/index'
import { Route as EntitiesDetailImport } from './routes/entities/$id'
import { Route as MenuItemsListImport } from './routes/menu-items/index'
import { Route as MenuItemsDetailImport } from './routes/menu-items/$id'
import { Route as PostsListImport } from './routes/posts/index'
import { Route as PostsDetailImport } from './routes/posts/$id'
import { Route as CommentsListImport } from './routes/comments/index'
import { Route as CommentsDetailImport } from './routes/comments/$id'
import { Route as TestimonialsListImport } from './routes/testimonials/index'
import { Route as TestimonialsDetailImport } from './routes/testimonials/$id'
import { Route as ServicesPagesListImport } from './routes/services-pages/index'
import { Route as ServicesPagesDetailImport } from './routes/services-pages/$id'
import { Route as PagesListImport } from './routes/pages/index'
import { Route as PagesDetailImport } from './routes/pages/$id'
import { Route as SiteSettingsListImport } from './routes/site-settings/index'
import { Route as SiteSettingsDetailImport } from './routes/site-settings/$id'
import { Route as ReservationsListImport } from './routes/reservations/index'
import { Route as ReservationsDetailImport } from './routes/reservations/$id'
import { Route as MenuCategoriesListImport } from './routes/menu-categories/index'
import { Route as MenuCategoriesDetailImport } from './routes/menu-categories/$id'
import { Route as RestaurantTablesListImport } from './routes/restaurant-tables/index'
import { Route as RestaurantTablesDetailImport } from './routes/restaurant-tables/$id'
import { Route as OrdersListImport } from './routes/orders/index'
import { Route as OrdersDetailImport } from './routes/orders/$id'
import { Route as OrderItemsListImport } from './routes/order-items/index'
import { Route as OrderItemsDetailImport } from './routes/order-items/$id'

const IndexRoute = IndexImport.update({ id: '/', path: '/', getParentRoute: () => rootRoute } as any)
const AboutRoute = AboutImport.update({ path: '/about', getParentRoute: () => rootRoute } as any)
const ContactRoute = ContactImport.update({ path: '/contact', getParentRoute: () => rootRoute } as any)

const EntitiesListRoute = EntitiesListImport.update({ path: '/entities/', getParentRoute: () => rootRoute } as any)
const EntitiesDetailRoute = EntitiesDetailImport.update({ path: '/entities/$id', getParentRoute: () => rootRoute } as any)
const MenuItemsListRoute = MenuItemsListImport.update({ path: '/menu-items/', getParentRoute: () => rootRoute } as any)
const MenuItemsDetailRoute = MenuItemsDetailImport.update({ path: '/menu-items/$id', getParentRoute: () => rootRoute } as any)
const PostsListRoute = PostsListImport.update({ path: '/posts/', getParentRoute: () => rootRoute } as any)
const PostsDetailRoute = PostsDetailImport.update({ path: '/posts/$id', getParentRoute: () => rootRoute } as any)
const CommentsListRoute = CommentsListImport.update({ path: '/comments/', getParentRoute: () => rootRoute } as any)
const CommentsDetailRoute = CommentsDetailImport.update({ path: '/comments/$id', getParentRoute: () => rootRoute } as any)
const TestimonialsListRoute = TestimonialsListImport.update({ path: '/testimonials/', getParentRoute: () => rootRoute } as any)
const TestimonialsDetailRoute = TestimonialsDetailImport.update({ path: '/testimonials/$id', getParentRoute: () => rootRoute } as any)
const ServicesPagesListRoute = ServicesPagesListImport.update({ path: '/services-pages/', getParentRoute: () => rootRoute } as any)
const ServicesPagesDetailRoute = ServicesPagesDetailImport.update({ path: '/services-pages/$id', getParentRoute: () => rootRoute } as any)
const PagesListRoute = PagesListImport.update({ path: '/pages/', getParentRoute: () => rootRoute } as any)
const PagesDetailRoute = PagesDetailImport.update({ path: '/pages/$id', getParentRoute: () => rootRoute } as any)
const SiteSettingsListRoute = SiteSettingsListImport.update({ path: '/site-settings/', getParentRoute: () => rootRoute } as any)
const SiteSettingsDetailRoute = SiteSettingsDetailImport.update({ path: '/site-settings/$id', getParentRoute: () => rootRoute } as any)
const ReservationsListRoute = ReservationsListImport.update({ path: '/reservations/', getParentRoute: () => rootRoute } as any)
const ReservationsDetailRoute = ReservationsDetailImport.update({ path: '/reservations/$id', getParentRoute: () => rootRoute } as any)
const MenuCategoriesListRoute = MenuCategoriesListImport.update({ path: '/menu-categories/', getParentRoute: () => rootRoute } as any)
const MenuCategoriesDetailRoute = MenuCategoriesDetailImport.update({ path: '/menu-categories/$id', getParentRoute: () => rootRoute } as any)
const RestaurantTablesListRoute = RestaurantTablesListImport.update({ path: '/restaurant-tables/', getParentRoute: () => rootRoute } as any)
const RestaurantTablesDetailRoute = RestaurantTablesDetailImport.update({ path: '/restaurant-tables/$id', getParentRoute: () => rootRoute } as any)
const OrdersListRoute = OrdersListImport.update({ path: '/orders/', getParentRoute: () => rootRoute } as any)
const OrdersDetailRoute = OrdersDetailImport.update({ path: '/orders/$id', getParentRoute: () => rootRoute } as any)
const OrderItemsListRoute = OrderItemsListImport.update({ path: '/order-items/', getParentRoute: () => rootRoute } as any)
const OrderItemsDetailRoute = OrderItemsDetailImport.update({ path: '/order-items/$id', getParentRoute: () => rootRoute } as any)

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AboutRoute,
  ContactRoute,
  EntitiesListRoute,
  EntitiesDetailRoute,
  MenuItemsListRoute,
  MenuItemsDetailRoute,
  PostsListRoute,
  PostsDetailRoute,
  CommentsListRoute,
  CommentsDetailRoute,
  TestimonialsListRoute,
  TestimonialsDetailRoute,
  ServicesPagesListRoute,
  ServicesPagesDetailRoute,
  PagesListRoute,
  PagesDetailRoute,
  SiteSettingsListRoute,
  SiteSettingsDetailRoute,
  ReservationsListRoute,
  ReservationsDetailRoute,
  MenuCategoriesListRoute,
  MenuCategoriesDetailRoute,
  RestaurantTablesListRoute,
  RestaurantTablesDetailRoute,
  OrdersListRoute,
  OrdersDetailRoute,
  OrderItemsListRoute,
  OrderItemsDetailRoute,
])
